import Link from "next/link";
import { AlertCircle, ArrowLeft, CheckCircle2, CircleHelp, TrendingDown } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AssessmentQuestionCard } from "@/components/question-card";
import { Badge } from "@/components/ui/badge";
import { assessment, getStudent, transferOutcomes } from "@/lib/demo-data";
import { getOutcomeCounts } from "@/lib/analysis";

export const metadata = { title: "Class outcomes" };

export default function OutcomesPage() {
  const counts = getOutcomeCounts(transferOutcomes);
  return <AppShell active="analysis"><div className="page-width page-stack"><Link href="/analyses/demo" className="back-link"><ArrowLeft size={16} /> Back to analysis</Link><header className="outcomes-header"><div><span className="eyebrow">Transfer check complete</span><h1>Most learners revised the model.</h1><p>Evidence from a new radius scale shows where understanding held—and where teacher follow-up still matters.</p></div><Badge tone="green">9 of 12 resolved</Badge></header><AssessmentQuestionCard assessment={assessment} compact /><section className="outcome-comparison"><div className="comparison-label"><span className="eyebrow"><TrendingDown size={15} /> Before and after</span><h2>Misconception load</h2></div><div className="comparison-side"><span>Before intervention</span><strong>9</strong><div className="bar before" style={{ "--bar": "75%" } as React.CSSProperties} /><small>learners in misconception clusters</small></div><div className="comparison-arrow">→</div><div className="comparison-side"><span>After transfer check</span><strong>3</strong><div className="bar after" style={{ "--bar": "25%" } as React.CSSProperties} /><small>uncertain or requiring follow-up</small></div></section><section className="outcome-status-grid"><article className="status-resolved"><CheckCircle2 size={21} /><div><strong>{counts.resolved}</strong><span>Resolved</span><p>Reasoning transferred to a new scale factor.</p></div></article><article className="status-uncertain"><CircleHelp size={21} /><div><strong>{counts.uncertain}</strong><span>Uncertain</span><p>Correct answer with incomplete evidence.</p></div></article><article className="status-follow"><AlertCircle size={21} /><div><strong>{counts["follow-up"]}</strong><span>Teacher follow-up</span><p>The original misconception persisted.</p></div></article></section><section><div className="section-heading-row"><div><span className="eyebrow">Response evidence</span><h2>What changed in their thinking</h2></div><p>Synthetic student labels</p></div><div className="evidence-cards">{transferOutcomes.map((outcome) => { const student = getStudent(outcome.studentId); return student ? <article key={outcome.studentId}><div><span className="student-monogram">{student.label.slice(-2)}</span><div><strong>{student.label}</strong><small>Transfer answer: {outcome.transferAnswer}</small></div><Badge tone={outcome.status === "resolved" ? "green" : outcome.status === "uncertain" ? "amber" : "red"}>{outcome.status}</Badge></div><p>{outcome.evidence}</p></article> : null; })}</div></section></div></AppShell>;
}
